image: sikalabs/ci

stages:
  - build
  - deploy dev

variables:
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
  BASE_HOST: k8s.sikademo.com

build bin:
  stage: build
  image: golang
  script:
    - go build -o server-$GOOS-$GOARCH server.go
  artifacts:
    paths:
      - ./server-*
  rules:
    - if: $CI_COMMIT_BEFORE_SHA != "0000000000000000000000000000000000000000"
      changes:
        - server.go
  parallel:
    matrix:
      - GOOS:
          - linux
          - darwin
          - windows
        GOARCH:
          - amd64
          - arm64

build docker:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_MERGE_REQUEST_ID
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $IMAGE .
    - docker push $IMAGE

deploy dev:
  stage: deploy dev
  needs:
    - build docker
  variables:
    HOST: dev.$BASE_HOST
  script:
    - helm upgrade --install dev
        one-image --repo https://helm.sikalabs.io
        --set host=$HOST
        --set image=$IMAGE
    - slu wait-for tls -a $HOST:443
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - when: manual
  environment:
    name: dev
    url: https://$HOST
    on_stop: stop dev

stop dev:
  stage: deploy dev
  needs:
    - build docker
  variables:
    GIT_STRATEGY: none
  when: manual
  script:
    - helm uninstall dev
  environment:
    name: dev
    action: stop
